version: '3.8'

services:
  # --- INFRAESTRUTURA DE BANCO DE DADOS & CACHE ---
  postgres:
    image: postgres:15-alpine
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: encurtador-url
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - url_network

  redis:
    image: redis:7-alpine
    container_name: url_shortener_cache
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - url_network

    # --- Aplicação Spring Boot ---
  app:
    build: .
    container_name: url_shortener_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/encurtador-url
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - url_network

volumes:
  postgres_data:
  redis_data:

networks:
  url_network:
    driver: bridge