spring.application.name=encurtador-url
server.address=0.0.0.0


# Configuração do postgres como banco de dados de teste
spring.datasource.url=jdbc:postgresql://postgres:5432/encurtador-url
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração do Redis
spring.data.redis.database=0
spring.data.redis.host=localhost
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=60000